shariff.settings:
  type: config_object
  label: 'Shariff settings'
  mapping:
    shariff_hidden:
      type: boolean
      tabel: 'Hide block if Web Share API is supported'
    shariff_services:
      type: sequence
      label: 'Services'
      sequence:
        type: string
        label: 'Service'
    shariff_theme:
      type: string
      label: 'Shariff layout'
    shariff_css:
      type: string
      label: 'CSS variant'
    shariff_orientation:
      type: string
      label: 'Orientation of the buttons'
    shariff_twitter_via:
      type: string
      label: 'Twitter Via User'
    shariff_mail_url:
      type: string
      label: 'Mail link'
    shariff_mail_subject:
      type: string
      label: 'Mail subject'
    shariff_mail_body:
      type: string
      label: 'Mail body'
    shariff_referrer_track:
      type: string
      label: 'Referrer track code'
    shariff_backend_url:
      type: string
      label: 'Backend URL'
    shariff_flattr_category:
      type: string
      label: 'Flattr category'
    shariff_flattr_user:
      type: string
      label: 'Flattr user'
    shariff_media_url:
      type: string
      label: 'Media url'
    shariff_button_style:
      type: string
      label: 'Button layout'
    shariff_info_url:
      type: string
      label: 'Info Link'
    shariff_info_display:
      type: string
      label: 'Information display link'
    shariff_url:
      type: string
      label: 'Canonical URL'
    shariff_title:
      type: string
      label: 'Twitter/WhatsApp Title'
