core.entity_form_display.node.course_article.default:
  expected_config: {  }
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_content:
            label: Content
core.entity_form_display.node.course_section.default:
  expected_config: { }
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_section_content:
            label: 'Basic Information'
          group_settings:
            label: Settings
          group_visibility:
            label: 'Access permissions'
core.entity_form_display.node.course_video.default:
  expected_config: { }
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_content:
            label: Content