block.block.course_navigation:
  expected_config:
    visibility:
      request_path:
        pages: "/node/*/edit\r\n/node/*/delete"
  update_actions:
    change:
      visibility:
        request_path:
          pages: "/node/*/edit\r\n/node/*/delete\r\n/node/*/translations*"
block.block.socialblue_course_navigation:
  expected_config:
    visibility:
      request_path:
        pages: "/node/*/edit\r\n/node/*/delete"
  update_actions:
    change:
      visibility:
        request_path:
          pages: "/node/*/edit\r\n/node/*/delete\r\n/node/*/translations*"
block.block.course_material_pager:
  expected_config:
    visibility:
      request_path:
        pages: "/node/*/edit\r\n/node/*/delete"
  update_actions:
    change:
      visibility:
        request_path:
          pages: "/node/*/edit\r\n/node/*/delete\r\n/node/*/translations*"
