dependencies:
  module:
    - social_content_translation
    - content_translation
items:
  user.role.contentmanager:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'translate course_article node'
          - 'translate course_video node'
          - 'translate course_section node'