core.entity_form_display.group.course_basic.default:
  expected_config: { }
  update_actions:
    delete:
      hidden:
        path: true
    add:
      content:
        path:
          type: path
          weight: 30
          settings: { }
          third_party_settings: { }
          region: content
