<?php

/**
 * @file
 * Primary module hooks for Display Layout module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\display_layout\DisplayLayoutEntityViewAlter;
use Drupal\display_layout\Form\EntityViewDisplayLayoutEditForm;
use Drupal\display_layout\Form\LBEntityViewDisplayLayoutEditForm;

/**
 * Implements hook_entity_type_alter().
 */
function display_layout_entity_type_alter(array &$entity_types) {
  if (\Drupal::service('module_handler')->moduleExists('layout_builder')) {
    $entity_types['entity_view_display']->setFormClass('edit', LBEntityViewDisplayLayoutEditForm::class);
  }
  else {
    $entity_types['entity_view_display']->setFormClass('edit', EntityViewDisplayLayoutEditForm::class);
  }

}

/**
 * Implements hook_entity_view_alter().
 */
function display_layout_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  \Drupal::classResolver(DisplayLayoutEntityViewAlter::class)->alter($build, $entity, $display);
}
