<?php

/**
 * @file
 * Best Selling products module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function best_selling_products_theme() {
  return [
    'best_selling_products' => [
      'variables' => [
        'products' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_help().
 */
function best_selling_products_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the best_selling_products module.
    case 'help.page.best_selling_products':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Build and display "the best sales" block with products in your shop pages.') . '</p>';
      return $output;
  }
}
