social_geolocation.settings:
  type: config_object
  label: 'Social Geolocation settings'
  mapping:
    enabled:
      type: boolean
      label: 'Whether entities are processed and geolocation happen'
    site_manager_assist:
      type: boolean
      label: 'Whether the user should be shown a message to contact a site manager in case of a geolocation error'
    site_manager_contact:
      type: integer
      label: 'The User ID of the site manager that can be contacted in case of a geolocation error'
    geolocation_provider:
      type: string
      label: 'The choice for which provider to use to store geolocation data'
    unit_of_measurement:
      type: string
      label: 'Unit of measurement'
